images:
  enable_external_images: true
  placeholder_image: https://github.com/magetarro/news/blob/main/pexels-jeffrey-czum-254391-3750893.jpg?text=Telegram+Digest
publish_hour_local: 9
rules:
  exclude_domains_ru_affiliated: true
  exclude_languages:
  - ru
  fundraising_filter_keywords:
  - донат
  - донаты
  - донатить
  - сбор средств
  - сбор на
  - собираем на
  - поддержать канал
  - поддержать автора
  - пожертвования
  - пожертвовать
  - реквизиты
  - карта *
  - картой *
  - перевод на карту
  - qiwi
  - донат
  - донати
  - донатити
  - збір коштів
  - збір на
  - збираємо на
  - підтримати канал
  - підтримати автора
  - пожертви
  - пожертва
  - реквізити
  - переказ на картку
  - donate
  - donation
  - patreon
  - boosty
  - buymeacoffee
  - fundraiser
  - send money
  - paypal.me
  - 'crypto:'
  - 'btc:'
  - usdt
  summaries_ru_sentences:
  - 4
  - 5
  telegram_lookback_hours: 24
telegram:
  fact_summary:
  - ["https://rsshub.app/telegram/channel/ShrikeNews",
  "https://hub.slarker.me/telegram/channel/ShrikeNews",
  "https://rsshub.rssforever.com/telegram/channel/ShrikeNews"]
  - ["https://rsshub.app/telegram/channel/Yzheleznyak",
  "https://hub.slarker.me/telegram/channel/Yzheleznyak",
  "https://rsshub.rssforever.com/telegram/channel/Yzheleznyak"]
  - ["https://rsshub.app/telegram/channel/Zvizdecmanhustu",
  "https://hub.slarker.me/telegram/channel/Zvizdecmanhustu",
  "https://rsshub.rssforever.com/telegram/channel/Zvizdecmanhustu"]
  full_no_opinion:
  - ["https://rsshub.app/telegram/channel/Mccartneyser68",
  "https://hub.slarker.me/telegram/channel/Mccartneyser68",
  "https://rsshub.rssforever.com/telegram/channel/Mccartneyser68"]
  raw:
  - ["https://rsshub.app/telegram/channel/babchenko77",
  "https://hub.slarker.me/telegram/channel/babchenko77",
  "https://rsshub.rssforever.com/telegram/channel/babchenko77"]
  - ["https://rsshub.app/telegram/channel/resurgammmm",
  "https://hub.slarker.me/telegram/channel/resurgammmm",
  "https://rsshub.rssforever.com/telegram/channel/resurgammmm"]
timezone: America/Los_Angeles
topics: {}
