images:
  enable_external_images: true
  placeholder_image: https://via.placeholder.com/1200x630.png?text=Telegram+Digest
publish_hour_local: 9
rules:
  exclude_domains_ru_affiliated: true
  exclude_languages:
  - ru
  fundraising_filter_keywords:
  - донат
  - донаты
  - донатить
  - сбор средств
  - сбор на
  - собираем на
  - поддержать канал
  - поддержать автора
  - пожертвования
  - пожертвовать
  - реквизиты
  - карта *
  - картой *
  - перевод на карту
  - qiwi
  - донат
  - донати
  - донатити
  - збір коштів
  - збір на
  - збираємо на
  - підтримати канал
  - підтримати автора
  - пожертви
  - пожертва
  - реквізити
  - переказ на картку
  - donate
  - donation
  - patreon
  - boosty
  - buymeacoffee
  - fundraiser
  - send money
  - paypal.me
  - 'crypto:'
  - 'btc:'
  - usdt
  summaries_ru_sentences:
  - 4
  - 5
  telegram_lookback_hours: 24
telegram:
  fact_summary:
  - https://rsshub.app/telegram/channel/ShrikeNews
  - https://rsshub.app/telegram/channel/Yzheleznyak
  - https://rsshub.app/telegram/channel/Zvizdecmanhustu
  full_no_opinion:
  - https://rsshub.app/telegram/channel/Mccartneyser68
  raw:
  - https://rsshub.app/telegram/channel/babchenko77
  - https://rsshub.app/telegram/channel/resurgammmm
timezone: America/Los_Angeles
topics: {}
