name: ChatGPT-built RSS

on:
  schedule:
    - cron: "0 * * * *"   # hourly; script publishes only at 08:00 America/Los_Angeles
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser python-dateutil pytz lxml pyyaml

      - name: Build RSS with ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/chatgpt_build_rss.py

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add rss.xml
            git commit -m "Auto-update rss.xml (ChatGPT-built)"
            git push
          else
            echo "No changes."
          fi
